version: "3.9"

services:
  backend:
    image: arun586/ken-backend:ci
    build: ./backend
    container_name: ken-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ken
    restart: always

  frontend:
    image: arun586/ken-frontend:ci
    build: ./frontend
    container_name: ken-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  mysql:
    image: mysql:8
    container_name: ken-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ken
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
