version: "3.9"

services:
  frontend:
    build:
      context: ./lms   # root of lms folder
      dockerfile: frontend/dockerfile
    image: arun586/ken-frontend:prod
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./lms   # root of lms folder
      dockerfile: backend/dockerfile
    image: arun586/ken-backend:prod
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - STRIPE_SECRET_KEY=sk_test_1234567890
