version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ken-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ken
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ken-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    ports:
      - "5000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ken-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
