version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: arun586/ken-frontend:ci
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    # For production you might replace npm run dev with serving build output via nginx
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    image: arun586/ken-backend:ci
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    command: npm run dev
