version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: arun586/ken-frontend:ci
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: arun586/ken-backend:ci
    ports:
      - "5000:5000"
    depends_on:
      - frontend
    environment:
      - NODE_ENV=development
      - PORT=5000
    command: node server.js
