version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ken-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    restart: always

  frontend:
    build: ./frontend
    container_name: ken-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:5173"
    depends_on:
      - backend
    restart: always

  mysql:
    image: mysql:8
    container_name: ken-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ken
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
